### ISSUE TITLE
Log file Filling up Hard Drive Nightly

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#135]
Every night I am finding that a log file in the following path is growing past 800GB and filing up my root partition. 

/var/lib/docker/containers/da026dba49bcde8e0e3f2aed255060bc3f5c236cd21937406a3f2ce4fbe3d0d4/da026dba49bcde8e0e3f2aed255060bc3f5c236cd21937406a3f2ce4fbe3d0d4-json.log

The musicbrainz-docker_indexer is the docker id: da026dba49bc

How do I fix this problem without manually having to delete this file daily?

**Comment by SuperSandro2000** [comment]
How to limit the log files please refer to https://docs.docker.com/config/containers/logging/local/#usage but you should check those log files and check if there is some boot looping or other error ocuring.
If you want us to take a closer look at the log files you could paste a short snipped which represents most of the content of the file.

ps Those ids are generated randomly and are not very useful to us.

**Comment by yvanzo** [comment]
There are known issues with the indexer but never had a log file growing past 800GB. I would be interested in seeing the last lines of this log file to identify which issue in indexer is causing this on your instance. Can be retrieved with:
```sh
docker-compose logs --tail=50 --timestamps indexer
```

**Comment by JoshDi** [comment]
I will send this next time it happens. thank you

**Comment by JoshDi** [comment]
Here is the error I am getting when running this command:

```
root@HTPC-Xeon:/storage/musicbrainz-docker# docker-compose logs --tail=50 --timestamps indexer
Attaching to musicbrainz-docker_indexer_1
indexer_1      | 2020-04-29T17:33:00.286298791Z 2020-04-29 17:33:00,286: Batch size is set to 200
indexer_1      | 2020-04-29T17:33:00.286351778Z 2020-04-29 17:33:00,286: Process delay is set to 15 seconds
indexer_1      | 2020-04-29T17:33:00.286419284Z 2020-04-29 17:33:00,286: Index limit is set to 200000 rows
indexer_1      | 2020-04-29T17:33:00.288021489Z 2020-04-29 17:33:00,287: AMQP timeout is set to 30 seconds
indexer_1      | 2020-04-29T17:33:00.298954145Z 2020-04-29 17:33:00,298: Retrying...
indexer_1      | 2020-04-29T17:33:00.299272321Z 2020-04-29 17:33:00,298: Basic.consume: (404) NOT_FOUND - no queue 'search.index' in vhost '                            /search-index-rebuilder'
indexer_1      | 2020-04-29T17:33:00.299289452Z Traceback (most recent call last):
indexer_1      | 2020-04-29T17:33:00.299293954Z   File "/usr/local/lib/python2.7/site-packages/retrying.py", line 200, in call
indexer_1      | 2020-04-29T17:33:00.299297787Z     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
indexer_1      | 2020-04-29T17:33:00.299301110Z   File "sir/amqp/handler.py", line 451, in _watch_impl
indexer_1      | 2020-04-29T17:33:00.299314901Z     handler.connect_to_rabbitmq()
indexer_1      | 2020-04-29T17:33:00.299318080Z   File "sir/amqp/handler.py", line 205, in connect_to_rabbitmq
indexer_1      | 2020-04-29T17:33:00.299320935Z     add_handler("search.index", self.index_callback, ch)
indexer_1      | 2020-04-29T17:33:00.299323798Z   File "sir/amqp/handler.py", line 184, in add_handler
indexer_1      | 2020-04-29T17:33:00.299326695Z     channel.basic_consume(queue, callback=handler)
indexer_1      | 2020-04-29T17:33:00.299329392Z   File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 1788, in basic_consume
indexer_1      | 2020-04-29T17:33:00.299342790Z     (60, 21),  # Channel.basic_consume_ok
indexer_1      | 2020-04-29T17:33:00.299346806Z   File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 69, in wait
indexer_1      | 2020-04-29T17:33:00.299349764Z     return self.dispatch_method(method_sig, args, content)
indexer_1      | 2020-04-29T17:33:00.299352581Z   File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 87, in dispat                            ch_method
indexer_1      | 2020-04-29T17:33:00.299355486Z     return amqp_method(self, args)
indexer_1      | 2020-04-29T17:33:00.299358160Z   File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 243, in _close
indexer_1      | 2020-04-29T17:33:00.299361014Z     reply_code, reply_text, (class_id, method_id), ChannelError,
indexer_1      | 2020-04-29T17:33:00.299363859Z NotFound: Basic.consume: (404) NOT_FOUND - no queue 'search.index' in vhost '/search-index-r                            ebuilder'
indexer_1      | 2020-04-29T17:33:00.299424709Z 2020-04-29 17:33:00,299: Retrying in 30 seconds
indexer_1      | 2020-04-29T17:33:30.362297321Z 2020-04-29 17:33:30,362: Batch size is set to 200
indexer_1      | 2020-04-29T17:33:30.362339696Z 2020-04-29 17:33:30,362: Process delay is set to 15 seconds
indexer_1      | 2020-04-29T17:33:30.362383712Z 2020-04-29 17:33:30,362: Index limit is set to 200000 rows
indexer_1      | 2020-04-29T17:33:30.363043852Z 2020-04-29 17:33:30,362: AMQP timeout is set to 30 seconds
indexer_1      | 2020-04-29T17:33:30.371193150Z 2020-04-29 17:33:30,370: Retrying...
indexer_1      | 2020-04-29T17:33:30.371241971Z 2020-04-29 17:33:30,371: Basic.consume: (404) NOT_FOUND - no queue 'search.index' in vhost '                            /search-index-rebuilder'
indexer_1      | 2020-04-29T17:33:30.371255954Z Traceback (most recent call last):
indexer_1      | 2020-04-29T17:33:30.371259256Z   File "/usr/local/lib/python2.7/site-packages/retrying.py", line 200, in call
indexer_1      | 2020-04-29T17:33:30.371261781Z     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
indexer_1      | 2020-04-29T17:33:30.371264263Z   File "sir/amqp/handler.py", line 451, in _watch_impl
indexer_1      | 2020-04-29T17:33:30.371266646Z     handler.connect_to_rabbitmq()
indexer_1      | 2020-04-29T17:33:30.371268800Z   File "sir/amqp/handler.py", line 205, in connect_to_rabbitmq
indexer_1      | 2020-04-29T17:33:30.371271861Z     add_handler("search.index", self.index_callback, ch)
indexer_1      | 2020-04-29T17:33:30.371274171Z   File "sir/amqp/handler.py", line 184, in add_handler
indexer_1      | 2020-04-29T17:33:30.371276389Z     channel.basic_consume(queue, callback=handler)
indexer_1      | 2020-04-29T17:33:30.371284339Z   File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 1788, in basic_consume
indexer_1      | 2020-04-29T17:33:30.371286717Z     (60, 21),  # Channel.basic_consume_ok
indexer_1      | 2020-04-29T17:33:30.371288823Z   File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 69, in wait
indexer_1      | 2020-04-29T17:33:30.371291067Z     return self.dispatch_method(method_sig, args, content)
indexer_1      | 2020-04-29T17:33:30.371293247Z   File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 87, in dispat                            ch_method
indexer_1      | 2020-04-29T17:33:30.371295498Z     return amqp_method(self, args)
indexer_1      | 2020-04-29T17:33:30.371297578Z   File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 243, in _close
indexer_1      | 2020-04-29T17:33:30.371299868Z     reply_code, reply_text, (class_id, method_id), ChannelError,
indexer_1      | 2020-04-29T17:33:30.371302068Z NotFound: Basic.consume: (404) NOT_FOUND - no queue 'search.index' in vhost '/search-index-r                            ebuilder'
indexer_1      | 2020-04-29T17:33:30.371456201Z 2020-04-29 17:33:30,371: Retrying in 30 seconds

```

**Comment by yvanzo** [comment]
It seems that AMQP has not been correctly set up, the indexer is repeatedly failing to retrieve index messages. Most probably something went wrong while setting up AMQP.

First, disable live indexing and restart RabbitMQ:

```bash
admin/configure rm live-indexing-search
docker-compose up -d indexer
docker-compose restart mq
```

Then refer to “[Enable live indexing](https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev#enable-live-indexing)”. If everything worked as expected, the error `(404) NOT_FOUND` should not show up again in `indexer` logs.

**Comment by yvanzo** [comment]
Logs disk usage is now limited.
