### ISSUE TITLE
AMQP Setup Fails connecting to RabbitMQ

### ISSUE THREAD

**Issue by slayer49** [metabrainz/musicbrainz-docker#151]
```
$ sudo docker-compose exec indexer python -m sir amqp_setup
2020-05-21 19:37:48,398: Connecting to RabbitMQ

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/sir/__main__.py", line 127, in <module>
    main()
  File "/code/sir/__main__.py", line 123, in main
    func(args)
  File "sir/amqp/setup.py", line 22, in setup_rabbitmq
    conn = util.create_amqp_connection()
  File "sir/util.py", line 138, in create_amqp_connection
    virtual_host=cget("vhost"),
  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/usr/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
socket.error: [Errno 104] Connection reset by peer

$ sudo docker-compose logs -f indexer

Attaching to musicbrainzdocker_indexer_1
indexer_1      | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
indexer_1      | *** Running /etc/rc.local...
indexer_1      | *** Booting runit daemon...
indexer_1      | *** Runit started as PID 9
indexer_1      | 2020/05/20 23:11:30 [DEBUG] (logging) enabling syslog on LOCAL0
indexer_1      | Consul Template returned errors:
indexer_1      | error setting up syslog logger: Unix syslog delivery error
indexer_1      | 2020/05/20 23:11:31 [DEBUG] (logging) enabling syslog on LOCAL0
indexer_1      | Cleaning up...
indexer_1      | *** Shutting down runit daemon (PID 9)...
indexer_1      | *** Killing all processes...
indexer_1      | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
indexer_1      | *** Running /etc/rc.local...
indexer_1      | *** Booting runit daemon...
indexer_1      | *** Runit started as PID 9
indexer_1      | 2020/05/21 19:36:24 [DEBUG] (logging) enabling syslog on LOCAL0
indexer_1      | Consul Template returned errors:
indexer_1      | error setting up syslog logger: Unix syslog delivery error
indexer_1      | May 21 19:36:24 e66c63309fef syslog-ng[18]: syslog-ng starting up; version='3.5.6'
indexer_1      | 2020/05/21 19:36:25 [DEBUG] (logging) enabling syslog on LOCAL0
```

I apologize for the bad formatting I couldn't get the logs to look any cleaner in the code blocks.

**Comment by slayer49** [comment]
forgot to post the mq log.   invalid credentials:
```
mq1           | 2020-05-21T19:18:43.480633617Z =INFO REPORT==== 21-May-2020::19:18:42 ===
mq_1           | 2020-05-21T19:18:43.480655741Z accepting AMQP connection <0.1979.0> (172.18.0.6:45480 -> 172.18.0.5:5672)
mq_1           | 2020-05-21T19:18:44.665271362Z
mq_1           | 2020-05-21T19:18:44.665459470Z =ERROR REPORT==== 21-May-2020::19:18:44 ===
mq_1           | 2020-05-21T19:18:44.665480229Z Error on AMQP connection <0.1979.0> (172.18.0.6:45480 -> 172.18.0.5:5672, state: starting):
mq_1           | 2020-05-21T19:18:44.665497220Z AMQPLAIN login refused: user 'sir' - invalid credentials
mq_1           | 2020-05-21T19:18:47.836582692Z
mq_1           | 2020-05-21T19:18:47.836783408Z =INFO REPORT==== 21-May-2020::19:18:47 ===
mq_1           | 2020-05-21T19:18:47.836803618Z closing AMQP connection <0.1979.0> (172.18.0.6:45480 -> 172.18.0.5:5672)
mq_1           | 2020-05-21T19:37:48.439384903Z
mq_1           | 2020-05-21T19:37:48.439525602Z =INFO REPORT==== 21-May-2020::19:37:48 ===
mq_1           | 2020-05-21T19:37:48.439545872Z accepting AMQP connection <0.2042.0> (172.18.0.6:45490 -> 172.18.0.5:5672)
mq_1           | 2020-05-21T19:37:48.457758794Z
mq_1           | 2020-05-21T19:37:48.457885667Z =ERROR REPORT==== 21-May-2020::19:37:48 ===
mq_1           | 2020-05-21T19:37:48.457902904Z Error on AMQP connection <0.2042.0> (172.18.0.6:45490 -> 172.18.0.5:5672, state: starting):
mq_1           | 2020-05-21T19:37:48.457920040Z AMQPLAIN login refused: user 'sir' - invalid credentials
mq_1           | 2020-05-21T19:37:51.458718915Z
mq_1           | 2020-05-21T19:37:51.458806973Z =INFO REPORT==== 21-May-2020::19:37:51 ===
mq_1           | 2020-05-21T19:37:51.458824093Z closing AMQP connection <0.2042.0> (172.18.0.6:45490 -> 172.18.0.5:5672)
```

**Comment by yvanzo** [comment]
It seems that your `mq` instance did not create user `sir` as expected. Try restarting it:

```bash
sudo docker-compose restart mq && \
sudo docker-compose logs -t mq | grep Creating
```

P.S. No problem, I reformatted your comments using three back ticks ` ``` ` for code blocks.

**Comment by slayer49** [comment]
Hi, I only see a guest user created.

``` 
 $ sudo docker-compose logs -t mq | grep Creating
mq_1           | 2020-05-20T18:08:30.263127403Z Creating user 'guest'
```

**Comment by yvanzo** [comment]
Recreating the container should set configuration back:
```bash
sudo docker-compose up --force-recreate -d mq && \
sudo docker-compose logs --follow -t mq
```

**Comment by slayer49** [comment]
This solved the issue, thanks.
