### ISSUE TITLE
about database index

### ISSUE THREAD

**Issue by CZILYYZ** [metabrainz/musicbrainz-docker#274]
when i finish the command:"sudo docker-compose run --rm musicbrainz fetch-dump.sh search", it works good,when i enter command :"sudo docker-compose run --rm search load-search-indexes.sh --force",it retrun:
"Thu Apr  4 16:57:00 UTC 2024: Load annotation search index...
Thu Apr  4 16:57:06 UTC 2024: Load area search index...
Thu Apr  4 16:57:06 UTC 2024: Load artist search index...
Thu Apr  4 16:57:24 UTC 2024: Load cdstub search index...
Thu Apr  4 16:57:26 UTC 2024: Load event search index...
Thu Apr  4 16:57:28 UTC 2024: Load instrument search index...
Thu Apr  4 16:57:28 UTC 2024: Load label search index...
Thu Apr  4 16:57:30 UTC 2024: Load place search index...
Thu Apr  4 16:57:30 UTC 2024: Load recording search index...
su/*stdin*\ : Decoding error (36) : Corrupted block detected 
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
ERROR: 2"
how to fix it?
when i enter command :" sudo admin/check-search-indexes all"
it return "admin/check-search-indexes: line 166: column: command not found", what happed? please help me!

**Comment by yvanzo** [comment]
Hi,

> fetch-dump.sh […] works good […]
> load-search-indexes.sh […] returns […]
> su/stdin\ : Decoding error (36) : Corrupted block detected
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now

I reproduced these commands on a test instance and it worked.

This error message could mean that the downloaded archive is corrupted.
Do you confirm that the `fetch-dump.sh` command showed `recording.tar.zst: OK` when checking MD5 sums?

If so, did you have enough disk space on your host for loading the archives? Was there any search activity while loading dumps?

> admin/check-search-indexes: line 166: column: command not found

The command `column` is not available on your host system. It is part of the [standard collection of Linux utilities](https://en.wikipedia.org/wiki/Util-linux). What is your operating system?

**Comment by CZILYYZ** [comment]
thank you for your replay ,my operating system is ubuntu, i have do search activity while loading dumps, i have already forgot if "recording.tar.zst: OK ",what i can do next ?

**Comment by CZILYYZ** [comment]
> Hi,
> 
> > fetch-dump.sh […] works good […]
> > load-search-indexes.sh […] returns […]
> > su/stdin\ : Decoding error (36) : Corrupted block detected
> > tar: Unexpected EOF in archive
> > tar: Error is not recoverable: exiting now
> 
> I reproduced these commands on a test instance and it worked.
> 
> This error message could mean that the downloaded archive is corrupted. Do you confirm that the `fetch-dump.sh` command showed `recording.tar.zst: OK` when checking MD5 sums?
> 
> If so, did you have enough disk space on your host for loading the archives? Was there any search activity while loading dumps?
> 
> > admin/check-search-indexes: line 166: column: command not found
> 
> The command `column` is not available on your host system. It is part of the [standard collection of Linux utilities](https://en.wikipedia.org/wiki/Util-linux). What is your operating system?
thank you for your replay ,my operating system is ubuntu, i have do search activity while loading dumps, i have already forgot if "recording.tar.zst: OK ",what i can do next ?

**Comment by yvanzo** [comment]
> my operating system is ubuntu

Please install the package `bsdextrautils` to make the command `column` available.

**Comment by yvanzo** [comment]
> I  have already forgot if "recording.tar.zst: OK ",what i can do next ?

The most likely with the error is that the download was incomplete.

You can try to resume the download with:

```sh
sudo docker-compose run --rm musicbrainz fetch-dump.sh --wget-options --continue search
```

before trying to load dumps again.

**Comment by CZILYYZ** [comment]
now when i enter command " sudo docker-compose exec indexer python -m sir reindex"
it return :
"2024-04-07 05:54:15,634: Checking whether the versions of the Solr cores are supported
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/sir/__main__.py", line 134, in <module>
    main()
  File "/code/sir/__main__.py", line 130, in main
    func(args)
  File "sir/indexing.py", line 54, in reindex
    util.check_solr_cores_version(entities)
  File "sir/util.py", line 123, in check_solr_cores_version
    map(solr_version_check, cores)
  File "sir/util.py", line 106, in solr_version_check
    u = urllib2.urlopen("%s/%s/schema/version" % (solr_uri, core))
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: search>""
what is wrong? how to fix it

**Comment by yvanzo** [comment]
Check the logs of your `search` service, but why would you want to rebuild search indexes if you did load search index dumps already?
