### ISSUE TITLE
Error when Indexing the database

### ISSUE THREAD

**Issue by nicolas-vazquez** [metabrainz/musicbrainz-docker#42]
After cloning this repo and following all the steps, when i have to index the database i run 
`sudo docker-compose run --rm indexer /home/search/index.sh`

But i always get the same error 

`ubuntu@ip-172-00-00-0:~/docker_server/musicbrainz-docker$ sudo docker-compose run --rm indexer /home/search/index.sh
Index Builder Started:21:07:35
org.postgresql.util.PSQLException: FATAL: database "musicbrainz_db" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:444)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:99)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:29)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:386)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.musicbrainz.search.index.IndexOptions.getMainDatabaseConnection(IndexOptions.java:52)
	at org.musicbrainz.search.index.IndexBuilder.main(IndexBuilder.java:110)
Exception in thread "main" java.lang.NullPointerException
	at org.musicbrainz.search.index.DatabaseIndex.readReplicationInformationFromDatabase(DatabaseIndex.java:112)
	at org.musicbrainz.search.index.IndexBuilder.main(IndexBuilder.java:147)
`

I've been trying to see where the database is created and change the name with no luck. 
I'm pretty sure it must be a pretty simple fix. 

Someone could please help me out with this one??
Thanks!!!

**Comment by nicolas-vazquez** [comment]
Thanks for your response. I made that change but I am getting this error now:

`Index Builder Started:19:28:16
recording: Unable to get replication information
tmp_artistcredit:Started at:19:28:16
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "artist_credit_name" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1592)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1327)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:336)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:328)
	at org.musicbrainz.search.index.CommonTables.createArtistCreditTableUsingDb(CommonTables.java:65)
	at org.musicbrainz.search.index.CommonTables.createTemporaryTables(CommonTables.java:197)
	at org.musicbrainz.search.index.IndexBuilder.main(IndexBuilder.java:151)`

Someone have experienced this?

Thanks!
